In [33]:
import numpy as np
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [43]:
a=np.zeros((3))
print(a)

[0. 0. 0.]


In [45]:
a[1]=9
print(a)

[0. 9. 0.]


In [47]:
a=np.arange(10,21,2)
print(a)

[10 12 14 16 18 20]


In [49]:
print(a+2)

[12 14 16 18 20 22]


In [51]:
print(a+2)

[12 14 16 18 20 22]


In [53]:
print(a*2)

[20 24 28 32 36 40]


In [55]:
print(np.sqrt(a))

[3.16227766 3.46410162 3.74165739 4.         4.24264069 4.47213595]


In [57]:
print(np.exp(a))

[2.20264658e+04 1.62754791e+05 1.20260428e+06 8.88611052e+06
 6.56599691e+07 4.85165195e+08]


In [59]:
print(np.tan(a))

[ 0.64836083 -0.63585993  7.24460662  0.30063224 -1.13731371  2.23716094]


In [63]:
print(np.cos(a))

[-0.83907153  0.84385396  0.13673722 -0.95765948  0.66031671  0.40808206]


In [69]:
print(a[a>13])

[14 16 18 20]


In [77]:
print(a.reshape(2,3))

[[10 12 14]
 [16 18 20]]


In [79]:
print(a.T)

[10 12 14 16 18 20]


In [85]:
print(np.argmin(a))

0
